datasources:
  hikari-base: &hikari-base
    connectionTimeout: 30001
    idleTimeout: 600001
    maxLifetime: 1800001
  datasource-one:
    username: "username-set-dynamically-in-test"
    password: "password-set-dynamically-in-test"
    url: "url-set-dynamically-in-test"
    hikari:
      <<: *hikari-base
      poolName: "one"
  datasource-two:
    username: "username-set-dynamically-in-test"
    password: "password-set-dynamically-in-test"
    url: "url-set-dynamically-in-test"
    hikari:
      <<: *hikari-base
      poolName: "two"